version: '3.9'
services:
  drone-server:
    image: drone/drone:2
    restart: always
    ports:
      - 8080:80
    volumes:
      - drone:/var/lib/drone
    env_file:
      - ./.env
    container_name: local_drone_server
  drone-runner:
    image: drone/drone-runner-docker
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - drone-server
    env_file:
      - ./.env
    container_name: local_drone_runner
volumes:
  drone:
